apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-subdir-external-provisioner

resources:
- namespace.yaml
- https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner//deploy/?timeout=120&ref=nfs-subdir-external-provisioner-4.0.18
