apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  entryPoints:
    - wireguard
  routes:
    - services:
      - name: wg-easy-wireguard
        port: 51820
        weight: 10
