apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
- managedByLabel

helmCharts:
- name: traefik-crds
  releaseName: traefik-crds
  version: v1.13.0
  repo: https://traefik.github.io/charts
  namespace: traefik
  valuesFile: values.yaml
