apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: obsidian-livesync
  namespace: obsidian-livesync
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`obsidian-livesync.libre.pod`)
      priority: 1
      middlewares:
        - name: obsidian-cors
          namespace: obsidian-livesync
      services:
        - name: obsidian-livesync
          port: 5984
          passHostHeader: true
