apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obsidian-livesync

resources:
- ../../base
- middleware.yaml
- ingressroute.yaml

secretGenerator:
- name: obsidian-livesync-secret
  type: Opaque
  literals:
  - COUCHDB_PASSWORD=changeme_couchdb_password
  - COUCHDB_SECRET=changeme_cookie_secret

images:
- name: couchdb
  newTag: "3.5.1"
