apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: argocd
    gethomepage.dev/description: ArgoCD
    gethomepage.dev/href: https://argocd.dev.insideaveritt.com
    gethomepage.dev/insecureSkipVerify: "true"
    gethomepage.dev/pod-selector: app.kubernetes.io/instance=argocd
    gethomepage.dev/group: 3rd Party
    gethomepage.dev/icon: argo-cd.png
    gethomepage.dev/weight: 10
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`argocd.libre.pod`)
    priority: 1
    services:
    - name: argocd
      port: http
