apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: baikal

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: baikal

resources:
- namespace.yaml
- pvc.yaml
- service.yaml
- deployment.yaml
