apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: vaultwarden

configMapGenerator:
- name: vaultwarden
  envs:
  - vaultwarden.env

resources:
- namespace.yaml
- pvc.yaml
- service.yaml
- deployment.yaml
