apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: step-ca

resources:
  - configmap-nginx.yaml
  - configmap-landing.yaml
  - service.yaml
  - ingressroute.yaml

patches:
  - path: patch-add-sidecar.yaml
