apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: root-ca-nginx-config
    files:
      - nginx.conf
  - name: root-ca-landing-page
    files:
      - index.html

generatorOptions:
  disableNameSuffixHash: true

resources:
  - service.yaml
  - ingressroute.yaml

patches:
  - path: patch-add-sidecar.yaml
