apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
- managedByLabel

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"

helmCharts:
- name: step-certificates
  version: 1.29.0
  releaseName: step-certificates
  namespace: step-ca
  repo: https://smallstep.github.io/helm-charts
  valuesFile: values.yaml
