apiVersion: v1
kind: Service
metadata:
  name: root-ca-server
  namespace: step-ca
  labels:
    app.kubernetes.io/name: root-ca-server
    app.kubernetes.io/component: ca-distribution
spec:
  selector:
    app.kubernetes.io/name: step-certificates
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
