apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
- managedByLabel

resources:
- certificate.yaml
- tlsstore.yaml

helmCharts:
- name: traefik
  releaseName: traefik
  version: v38.0.1
  repo: https://traefik.github.io/charts
  namespace: traefik
  valuesFile: values.yaml
