apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
- managedByLabel

# TODO: Remove namespace when installing apps from argocd appset
namespace: traefik

resources:
- namespace.yaml
- certificate.yaml
- tlsstore.yaml

helmCharts:
- name: traefik
  releaseName: traefik
  version: v38.0.1
  repo: https://traefik.github.io/charts
  namespace: traefik
  valuesFile: values.yaml
  includeCRDs: false
