apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
- managedByLabel

namespace: cert-manager

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: certificate-manager
    app.kubernetes.io/part-of: cert-manager

resources:
- namespace.yaml

helmCharts:
- name: cert-manager
  version: 1.19.2
  releaseName: cert-manager
  namespace: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
