# https://artifacthub.io/packages/helm/cert-manager/cert-manager

crds:
  enabled: true

featureGates: AdditionalCertificateOutputFormats=true
webhook:
  featureGates: AdditionalCertificateOutputFormats=true

# staging: https://acme-staging-v02.api.letsencrypt.org/directory`
# production: https://acme-v02.api.letsencrypt.org/directory
