apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: wg-easy

configMapGenerator:
- name: wg-easy
  envs:
  - wg-easy.env

resources:
- pvc.yaml
- service-http.yaml
- service-wireguard.yaml
- deployment.yaml
